// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SoutwestWater.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ProcessF4BFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ProcessF4B.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ProcessF4B", "\tIn order to start the Open Water Process F4b\r\n\tAs a SWWBS user \r\n\tI want to be a" +
                    "ble to create a service request  ", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "ProcessF4B")))
            {
                SoutwestWater.Features.ProcessF4BFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("A new service request can be created")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProcessF4B")]
        public virtual void ANewServiceRequestCanBeCreated()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A new service request can be created", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I am logged in as a SWWBS user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.And("I choose the \'Start Process\' link in the left hand menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And("I select create a new instance of process \'F04B NHH customer enquiries received b" +
                    "y Retailer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "RetailerName",
                        "RetailerID",
                        "RetailersOwnReference",
                        "ContactName",
                        "ContactNumber",
                        "ContactEmail"});
            table1.AddRow(new string[] {
                        "SWWBS",
                        "ret000000001",
                        "retailerOwnRef",
                        "contactName",
                        "071825728282",
                        "colinmontgomery@swwbs.co.uk"});
#line 10
 testRunner.And("In the Retailer Details section I add the values", ((string)(null)), table1, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "SPID",
                        "BuildingNumber",
                        "BuildingName",
                        "AddressLine1",
                        "AddressLine2",
                        "AddressLine3",
                        "Town",
                        "Postcode"});
            table2.AddRow(new string[] {
                        "1000000019S21",
                        "40",
                        "BuildingName",
                        "add 1",
                        "add2",
                        "add 3",
                        "London",
                        "BA12 6JH"});
#line 13
 testRunner.And("In the Eligible Premise Details section I add the values", ((string)(null)), table2, "And ");
#line 16
 testRunner.And("In the Drinking water enquiries or concerns section I select \'Request for informa" +
                    "tion about fluoride levels\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "DetailsOfEnquiry"});
            table3.AddRow(new string[] {
                        "These are the details of enquiry that I want to enter into the text area box"});
#line 17
 testRunner.And("In the Details Of Enquiry section I enter the text below", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "GiveConsent",
                        "ContactName",
                        "ContactNumber",
                        "NotifiedOfVisitDate"});
            table4.AddRow(new string[] {
                        "Yes",
                        "contact name",
                        "07822828282",
                        "Yes"});
#line 20
 testRunner.And("In the Consent to Contact the Non Household Customer section I add", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Signature",
                        "Date",
                        "FullName",
                        "RoleInTheCompany"});
            table5.AddRow(new string[] {
                        "signature",
                        "now",
                        "gary t gibbons",
                        "tester"});
#line 23
 testRunner.And("In the Declaration section I enter", ((string)(null)), table5, "And ");
#line 26
 testRunner.When("I click the \'Submit\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 27
 testRunner.Then("\'Your data was successfully submitted.\' message is displayed to the user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 28
 testRunner.And("I choose the \'Processes\' link in the left hand menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("I select \'F. Monitoring\' and sub process \'F04B NHH customer enquiries received by" +
                    " Retailer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("the submitted process can be seen in the processes I started list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("I can create a service request for all Process F4 enquiry Types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProcessF4B")]
        public virtual void ICanCreateAServiceRequestForAllProcessF4EnquiryTypes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can create a service request for all Process F4 enquiry Types", ((string[])(null)));
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
    testRunner.Given("I have added valid data to all sections of the Process F4 form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 34
 testRunner.When("In the Drinking water enquiries or concerns section I select all checkbox options" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
 testRunner.And("I click the \'Submit\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.Then("\'Your data was successfully submitted.\' message is displayed to the user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 37
 testRunner.And("I choose the \'Processes\' link in the left hand menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.And("I select \'F. Monitoring\' and sub process \'F04B NHH customer enquiries received by" +
                    " Retailer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.And("the submitted process can be seen in the processes I started list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("A wholsaler can accept a F4b process submission from a retailer and complete the " +
            "process")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProcessF4B")]
        public virtual void AWholsalerCanAcceptAF4BProcessSubmissionFromARetailerAndCompleteTheProcess()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A wholsaler can accept a F4b process submission from a retailer and complete the " +
                    "process", ((string[])(null)));
#line 41
this.ScenarioSetup(scenarioInfo);
#line 42
    testRunner.Given("I have added valid data to all sections of the Process F4 form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 43
 testRunner.And("In the Drinking water enquiries or concerns section I select \'Request for informa" +
                    "tion about fluoride levels\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
 testRunner.And("I click the \'Submit\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
 testRunner.And("\'Your data was successfully submitted.\' message is displayed to the user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.And("I log in as a wholesaler", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
 testRunner.And("I choose the \'Processes\' link in the left hand menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.And("I select \'F. Monitoring\' and sub process \'F04B NHH customer enquiries received by" +
                    " Retailer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.And("I open the process", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
 testRunner.And("I expand the left hand column", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.And("I click on the WSD link to progress the process", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
 testRunner.And("As a WSD user I accept the process", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.And("As a WSD I click the \'Save & Submit\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "AnswerToEnquiry"});
            table6.AddRow(new string[] {
                        "your query has been addressed"});
#line 54
 testRunner.When("I enter an answer to the retailer and submit", ((string)(null)), table6, "When ");
#line 57
 testRunner.And("I go to the retailer notification page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "to",
                        "from",
                        "subject",
                        "message"});
            table7.AddRow(new string[] {
                        "Gary GIBBONS",
                        "Sequence WSD User 2",
                        "Notification: Service Request Complete",
                        "Your Service Request"});
#line 58
 testRunner.Then("the retailer will receive notification of completion", ((string)(null)), table7, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("A wholesaler can reject a F4b process from a retailer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProcessF4B")]
        public virtual void AWholesalerCanRejectAF4BProcessFromARetailer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A wholesaler can reject a F4b process from a retailer", ((string[])(null)));
#line 62
this.ScenarioSetup(scenarioInfo);
#line 63
    testRunner.Given("I have added valid data to all sections of the Process F4 form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 64
    testRunner.And("In the Drinking water enquiries or concerns section I select \'Request for informa" +
                    "tion about fluoride levels\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
 testRunner.And("I click the \'Submit\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
 testRunner.And("\'Your data was successfully submitted.\' message is displayed to the user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
 testRunner.And("I log in as a wholesaler", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
 testRunner.And("I choose the \'Processes\' link in the left hand menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
 testRunner.And("I select \'F. Monitoring\' and sub process \'F04B NHH customer enquiries received by" +
                    " Retailer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
 testRunner.And("I open the process", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
 testRunner.And("I expand the left hand column", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
 testRunner.And("I click on the WSD link to progress the process", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 73
 testRunner.And("As a WSD user I reject the process and add the reason \'unknown contact is the rea" +
                    "son\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
 testRunner.When("As a WSD I click the \'Save & Submit\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 75
 testRunner.Then("An Update Service Request item is created informing the retailer group that the p" +
                    "rocess has been rejected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 76
 testRunner.And("the rejection reason is \'unknown contact is the reason\'\'f4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void AWholesalerCanRejectAF4ProcessFromARetailerUsingAllReasonsWhereTheProcessCanContinue(string rejectType, string page, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A wholesaler can reject a F4 process from a retailer using all reasons where the " +
                    "process can continue", exampleTags);
#line 78
this.ScenarioSetup(scenarioInfo);
#line 79
 testRunner.Given("I have added valid data to all sections of the Process F4 form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 80
    testRunner.And("In the Drinking water enquiries or concerns section I select \'Request for informa" +
                    "tion about fluoride levels\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
 testRunner.And("I click the \'Submit\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 82
 testRunner.And("I log in as a wholesaler", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.And("I choose the \'Processes\' link in the left hand menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
 testRunner.And("I select \'F. Monitoring\' and sub process \'F04B NHH customer enquiries received by" +
                    " Retailer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
 testRunner.And("I open the process", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 86
 testRunner.And("I expand the left hand column", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
 testRunner.And("I click on the WSD link to progress the process", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.When(string.Format("a wholesaler rejects the process instance with reason \'unknown contact is the rea" +
                        "son\' and \'{0}\'", rejectType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
 testRunner.And("As a WSD I click the \'Save & Submit\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
 testRunner.Then("An Update Service Request item is created informing the retailer group that the p" +
                    "rocess has been rejected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 91
 testRunner.And("the rejection reason is \'unknown contact is the reason\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("A wholesaler can reject a F4 process from a retailer using all reasons where the " +
            "process can continue: Incomplete form (Reject)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProcessF4B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Incomplete form (Reject)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:rejectType", "Incomplete form (Reject)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:page", "f4")]
        public virtual void AWholesalerCanRejectAF4ProcessFromARetailerUsingAllReasonsWhereTheProcessCanContinue_IncompleteFormReject()
        {
            this.AWholesalerCanRejectAF4ProcessFromARetailerUsingAllReasonsWhereTheProcessCanContinue("Incomplete form (Reject)", "f4", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("A wholesaler can reject a F4 process from a retailer using all reasons where the " +
            "process can continue: Further clarification required (Reject)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProcessF4B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Further clarification required (Reject)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:rejectType", "Further clarification required (Reject)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:page", "f4")]
        public virtual void AWholesalerCanRejectAF4ProcessFromARetailerUsingAllReasonsWhereTheProcessCanContinue_FurtherClarificationRequiredReject()
        {
            this.AWholesalerCanRejectAF4ProcessFromARetailerUsingAllReasonsWhereTheProcessCanContinue("Further clarification required (Reject)", "f4", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("A wholesaler can reject a F4 process from a retailer using all reasons where the " +
            "process can continue: Other - refer to explanatory text (Reject)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProcessF4B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Other - refer to explanatory text (Reject)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:rejectType", "Other - refer to explanatory text (Reject)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:page", "f4")]
        public virtual void AWholesalerCanRejectAF4ProcessFromARetailerUsingAllReasonsWhereTheProcessCanContinue_Other_ReferToExplanatoryTextReject()
        {
            this.AWholesalerCanRejectAF4ProcessFromARetailerUsingAllReasonsWhereTheProcessCanContinue("Other - refer to explanatory text (Reject)", "f4", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("A reject reason must be added in order for a wholesaler to reject a F4b process")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProcessF4B")]
        public virtual void ARejectReasonMustBeAddedInOrderForAWholesalerToRejectAF4BProcess()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A reject reason must be added in order for a wholesaler to reject a F4b process", ((string[])(null)));
#line 99
this.ScenarioSetup(scenarioInfo);
#line 100
    testRunner.Given("I have added valid data to all sections of the Process F4 form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 101
    testRunner.And("In the Drinking water enquiries or concerns section I select \'Request for informa" +
                    "tion about fluoride levels\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 102
 testRunner.And("I click the \'Submit\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 103
 testRunner.And("\'Your data was successfully submitted.\' message is displayed to the user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 104
 testRunner.And("I log in as a wholesaler", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.And("I choose the \'Processes\' link in the left hand menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 106
 testRunner.And("I select \'F. Monitoring\' and sub process \'F04B NHH customer enquiries received by" +
                    " Retailer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 107
 testRunner.And("I open the process", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
 testRunner.And("I expand the left hand column", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 109
 testRunner.And("I click on the WSD link to progress the process", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 110
 testRunner.And("As a WSD user I reject the process and fail to add a reason", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 111
 testRunner.When("As a WSD I click the \'Save & Submit\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "errormessage",
                        "page"});
            table8.AddRow(new string[] {
                        "Reject Reason is a Required Field",
                        "wholesale"});
#line 112
 testRunner.Then("an the verify request error messages is relayed to the user", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validation messages are relayed to the user when they omit mandatory information " +
            "from the F/01 form.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProcessF4B")]
        public virtual void ValidationMessagesAreRelayedToTheUserWhenTheyOmitMandatoryInformationFromTheF01Form_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validation messages are relayed to the user when they omit mandatory information " +
                    "from the F/01 form.", ((string[])(null)));
#line 116
this.ScenarioSetup(scenarioInfo);
#line 117
 testRunner.Given("I am logged in as a SWWBS user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 118
 testRunner.And("I choose the \'Start Process\' link in the left hand menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 119
 testRunner.And("I select create a new instance of process \'F04B NHH customer enquiries received b" +
                    "y Retailer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Signature",
                        "Date",
                        "FullName",
                        "RoleInTheCompany"});
            table9.AddRow(new string[] {
                        "",
                        "",
                        "",
                        ""});
#line 120
 testRunner.And("In the Declaration section I enter", ((string)(null)), table9, "And ");
#line 123
 testRunner.When("I click the \'Submit\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "errormessage",
                        "page"});
            table10.AddRow(new string[] {
                        "Retailer\'s Own Reference is a Required Field",
                        "retailer"});
            table10.AddRow(new string[] {
                        "Contact Name is a Required Field",
                        "retailer"});
            table10.AddRow(new string[] {
                        "Contact Number is a Required Field",
                        "retailer"});
            table10.AddRow(new string[] {
                        "Contact E-mail is a Required Field",
                        "retailer"});
            table10.AddRow(new string[] {
                        "SPID is a Required Field",
                        "retailer"});
            table10.AddRow(new string[] {
                        "Address Line 1 is a Required Field",
                        "retailer"});
            table10.AddRow(new string[] {
                        "Town is a Required Field",
                        "retailer"});
            table10.AddRow(new string[] {
                        "Postcode is a Required Field",
                        "retailer"});
            table10.AddRow(new string[] {
                        "Details of Enquiry is a Required Field",
                        "retailer"});
            table10.AddRow(new string[] {
                        "Role in the Company or Job Title is a Required Field",
                        "retailer"});
#line 124
    testRunner.Then("an the error messages below are relayed to the user", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void SPIDVerification(string sPIDValue, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SPID verification", exampleTags);
#line 137
this.ScenarioSetup(scenarioInfo);
#line 138
testRunner.Given("I am logged in as a SWWBS user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 139
testRunner.And("I choose the \'Start Process\' link in the left hand menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 140
testRunner.And("I select create a new instance of process \'F04B NHH customer enquiries received b" +
                    "y Retailer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 141
testRunner.When(string.Format("I add an invalid \'{0}\'", sPIDValue), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 142
testRunner.And("I click the \'Submit\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 143
testRunner.Then("The Invalid SPID error message is desplayed to the user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("SPID verification: dsjndjwwj")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProcessF4B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "dsjndjwwj")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SPID value", "dsjndjwwj")]
        public virtual void SPIDVerification_Dsjndjwwj()
        {
            this.SPIDVerification("dsjndjwwj", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("SPID verification: 1000000019S2G")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProcessF4B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "1000000019S2G")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SPID value", "1000000019S2G")]
        public virtual void SPIDVerification_1000000019S2G()
        {
            this.SPIDVerification("1000000019S2G", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("SPID verification: 1000000019S2112")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProcessF4B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "1000000019S2112")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SPID value", "1000000019S2112")]
        public virtual void SPIDVerification_1000000019S2112()
        {
            this.SPIDVerification("1000000019S2112", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("An incomplete process is saved")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProcessF4B")]
        public virtual void AnIncompleteProcessIsSaved()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("An incomplete process is saved", ((string[])(null)));
#line 151
this.ScenarioSetup(scenarioInfo);
#line 152
testRunner.Given("I am logged in as a SWWBS user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 153
 testRunner.And("I choose the \'Start Process\' link in the left hand menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 154
 testRunner.And("I select create a new instance of process \'F04B NHH customer enquiries received b" +
                    "y Retailer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "RetailerName",
                        "RetailerID",
                        "RetailersOwnReference",
                        "ContactName",
                        "ContactNumber",
                        "ContactEmail"});
            table11.AddRow(new string[] {
                        "SWWBS",
                        "ret100000001",
                        "retailerOwnRef",
                        "contactName",
                        "07816262525",
                        "winner@swwbs.co.uk"});
#line 155
 testRunner.And("In the Retailer Details section I add the values", ((string)(null)), table11, "And ");
#line 158
 testRunner.And("I click the \'Save All\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
 testRunner.And("I close the form window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 160
 testRunner.And("I choose the \'Processes\' link in the left hand menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 161
 testRunner.And("I select \'F. Monitoring\' and sub process \'F04B NHH customer enquiries received by" +
                    " Retailer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
 testRunner.When("I open the process", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "RetailerName",
                        "RetailerID",
                        "RetailersOwnReference",
                        "ContactName",
                        "ContactNumber",
                        "ContactEmail"});
            table12.AddRow(new string[] {
                        "SWWBS",
                        "ret100000001",
                        "retailerOwnRef",
                        "contactName",
                        "07816262525",
                        "winner@swwbs.co.uk"});
#line 163
 testRunner.Then("the Retailer Details values have been saved", ((string)(null)), table12, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("As a retailer i can cancel a request")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProcessF4B")]
        public virtual void AsARetailerICanCancelARequest()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As a retailer i can cancel a request", ((string[])(null)));
#line 167
this.ScenarioSetup(scenarioInfo);
#line 168
testRunner.Given("I have added valid data to all sections of the Process F4 form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 169
 testRunner.And("In the Drinking water enquiries or concerns section I select \'Request for informa" +
                    "tion about fluoride levels\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 170
 testRunner.And("I click the \'Submit\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 171
 testRunner.And("\'Your data was successfully submitted.\' message is displayed to the user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 172
 testRunner.And("I choose the \'Processes\' link in the left hand menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 173
 testRunner.And("I select \'F. Monitoring\' and sub process \'F04B NHH customer enquiries received by" +
                    " Retailer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 174
 testRunner.And("I open the process", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 175
 testRunner.And("I expand the left hand column", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 176
 testRunner.And("I click the Cancel Request option in the left hand column", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 177
 testRunner.When("I select the yes cancel radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 178
 testRunner.And("I enter the reason \'This is the reason for cancelling \'cancel reason\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 179
 testRunner.And("I click submit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 180
 testRunner.Then("the request will be cancelled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Retailer Name and Retailer Id are prepopulated")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ProcessF4B")]
        public virtual void RetailerNameAndRetailerIdArePrepopulated()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retailer Name and Retailer Id are prepopulated", ((string[])(null)));
#line 182
this.ScenarioSetup(scenarioInfo);
#line 183
 testRunner.Given("I am logged in as a SWWBS user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 184
 testRunner.And("I choose the \'Start Process\' link in the left hand menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 185
 testRunner.When("I select create a new instance of process \'F04B NHH customer enquiries received b" +
                    "y Retailer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 186
 testRunner.Then("the retailer name field and retailer id field are not empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
